### ISSUE TITLE
[Feature]: forge版本已经两个月没更新了

### ISSUE THREAD

**Issue by s4130** [continue-revolution/sd-forge-animatediff#14]
### Expected behavior

是不是该更新一下了,比如FreeInit功能

**Comment by continue-revolution** [comment]
度假中，度完假再抽空更新

**Comment by s4130** [comment]
是不是该更新了,现在我forge最新版本已经无法正常使用了qwq

**Comment by s4130** [comment]
> 是不是该更新了，现在我forge最新版本已经无法正常使用了qwq

测试

**Comment by s4130** [comment]
> 度假中，度完假再抽空更新

是不是该更新了，现在我forge最新版本已经无法正常使用了qwq
