### ISSUE TITLE
[Bug]: error on startup

### ISSUE THREAD

**Issue by Hugs288** [continue-revolution/sd-forge-animatediff#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

*** Error calling: J:\aistuff\stable-diffusion-webui\extensions\sd-forge-animatediff\scripts\animatediff.py/ui
    Traceback (most recent call last):
      File "J:\aistuff\stable-diffusion-webui\modules\scripts.py", line 564, in wrap_call
        return func(*args, **kwargs)
      File "J:\aistuff\stable-diffusion-webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 41, in ui
        unit = AnimateDiffUiGroup().render(
      File "J:\aistuff\stable-diffusion-webui\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 230, in render
        os.mkdir(model_dir)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'J:\\aistuff\\stable-diffusion-webui\\extensions\\sd-webui-animatediff\\model'

### Steps to reproduce the problem

start webui with extension enabled

### What should have happened?

extension to load properly

### Commit where the problem happens

webui: 43c9e3b5ce1642073c7a9684e36b45489eeb4a49
extension: c25a46d3dfacb60ea0d485d71f1aa78db2788d35

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
-
```

### Additional information

i have put multiple animate diff models in the folder.

**Comment by Hugs288** [comment]
fixed after installing on clean forge webui

**Comment by navin-hariharan** [comment]
@Hugs288 Is it working while generating?

**Comment by navin-hariharan** [comment]
#4 I am having this error!

**Comment by Hugs288** [comment]
> @Hugs288 Is it working while generating?

yes

**Comment by navin-hariharan** [comment]
> > @Hugs288 Is it working while generating?
> 
> yes

What GPU do you use?
