### ISSUE TITLE
[Bug]: it generates very blurry and pale pictures comparing to the original AnimateDiff with the identical params/models

### ISSUE THREAD

**Issue by zexcster** [continue-revolution/sd-forge-animatediff#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Try to generate any animation with animatediff-forge. it generates very blurry/pale pictures comparing to the original Animatediff

### Steps to reproduce the problem

1. Load any SD model, any sampling method (e.g. Euler a)
2. use default settings for everything, change resolution to 512x768, disable face restoration 
3. you can disable SD VAE or select any (does not affect results at all)
4. Use "A beautiful woman sings among trees" or "a cat sitting on grass"  (or any other you wish) as a text prompt
5. use the same seed for A1111 and A1111+forge (including other settings)
6. activate animatediff in A1111 and forge-animatediff in A1111 + forge
7. select the same motion module (does not matter which one, e.g. v2 or v3)
8. generate an animation

### What should have happened?

A1111+forge+animatediff should show detailed contrast results
instead it lacks of details and shows a pale picture comparing to the standard versions

### Commit where the problem happens

**A1111 forge:**
version: f0.0.14v1.8.0rc-latest-184-g43c9e3b5    
python: 3.10.11   
torch: 2.1.2+cu121    
xformers: 0.0.23.post1    
gradio: 3.41.2    
checkpoint: d37263937f
**sd-forge-animatediff extension:** 
forge-master	c25a46d3

**A1111**
version: v1.7.0    
python: 3.10.11    
torch: 2.0.1+cu118    
xformers: 0.0.20   
 gradio: 3.41.2    
checkpoint: d37263937f
**sd-webui-animatediff extension**
master	55ecff36

### Command Line Arguments

```Shell
--xformers
```

### Console logs

```Shell
no errors or difference in both versions
```

### Additional information

If you don't use animatediff extension the results are 99% identical (see the attached picture)
![animatediffvsforge](https://github.com/continue-revolution/sd-forge-animatediff/assets/39696348/0c061a3c-e4a8-4bbe-9c09-f38697d1fcba)

**Comment by continue-revolution** [comment]
there is some issue with forge backend (actually a comfy issue, related to alphas_cumprod) that I have already discovered but have not had a chance to resolve. I will attempt to resolve today.

**Comment by continue-revolution** [comment]
I have fixed this issue, waiting for lllyasviel to merge my pr. The pr is here. https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/475

You are free to checkout `conrevo/fix-alphas-cumprod` branch to get good and reproducable (I mean, from A1111) gif now. I don't know when lllyasviel will merge it.

**Comment by continue-revolution** [comment]
@lllyasviel This PR (https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/475) is extremely important. Can you please merge it?

**Comment by continue-revolution** [comment]
Fixed. You need to update forge. No need to update AnimateDiff extension.

**Comment by strawberrymelonpanda** [comment]
~Unfortunately, the PR's been reverted pending further review.  Hopefully not for too long.~
Nope, nevermind.  👍

**Comment by continue-revolution** [comment]
Don't worry, another PR has been merged and I don't think it will be reverted. You can get almostly the same result as A1111 now

**Comment by continue-revolution** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/478

**Comment by strawberrymelonpanda** [comment]
Nice work!  Sorry I didn't notice, they share the same PR title so slipped by me. 👍
